FOLDER_RULES = {
    'fachada': 'FACHADA', 'fachadas': 'FACHADA', 'externo': 'FACHADA', 'externa': 'FACHADA', 'frente': 'FACHADA',
    'piscina': 'PISCINA', 'pool': 'PISCINA',
    'academia': 'ACADEMIA', 'fitness': 'ACADEMIA', 'gym': 'ACADEMIA',
    'lazer': 'AREA_DE_LAZER', 'leisure': 'AREA_DE_LAZER', 'area comum': 'AREA_DE_LAZER', 'areas comuns': 'AREA_DE_LAZER',
    'salao': 'SALAO_DE_FESTAS', 'salon': 'SALAO_DE_FESTAS',
    'playground': 'PLAYGROUND',
    'plantas': 'PLANTA_BAIXA', 'planta': 'PLANTA_BAIXA', 'floor plans': 'PLANTA_BAIXA',
    'logo': 'LOGO', 'logos': 'LOGO', 'marca': 'LOGO', 'brand': 'LOGO',
    'video': 'VIDEO_TOUR', 'videos': 'VIDEO_TOUR', 'tour': 'VIDEO_TOUR',
    'drone': 'VIDEO_DRONE',
    'banner': 'BANNER', 'banners': 'BANNER',
    'social': 'POST_INSTAGRAM', 'instagram': 'POST_INSTAGRAM', 'posts': 'POST_INSTAGRAM',
    'interiores': 'SALA', 'interior': 'SALA',
    'quarto': 'QUARTO', 'quartos': 'QUARTO', 'suites': 'QUARTO', 'suite': 'QUARTO',
    'sala': 'SALA', 'living': 'SALA',
    'cozinha': 'COZINHA', 'kitchen': 'COZINHA',
    'banheiro': 'BANHEIRO', 'bath': 'BANHEIRO',
    'varanda': 'VARANDA', 'sacada': 'VARANDA', 'balcony': 'VARANDA',
    'gourmet': 'AREA_GOURMET',
    'obra': 'OBRA', 'construcao': 'OBRA',
    'documentos': 'PDF_FOLDER', 'documents': 'PDF_FOLDER', 'pdfs': 'PDF_FOLDER',
    'tabela': 'TABELA_PRECO', 'precos': 'TABELA_PRECO',
    'memorial': 'PDF_MEMORIAL',
    'mapa': 'MAPA_LOCALIZACAO', 'localizacao': 'MAPA_LOCALIZACAO',
}
