export type Plan = 'FREE' | 'STARTER' | 'PROFESSIONAL' | 'ENTERPRISE'
export type Role = 'SUPER_ADMIN' | 'ADMIN' | 'EDITOR' | 'VIEWER'
export type StatusEmpreendimento = 'RASCUNHO' | 'EM_REVISAO' | 'PUBLICADO' | 'ARQUIVADO'

export type ImportStatus =
  | 'AGUARDANDO'
  | 'VERIFICANDO_FONTE'
  | 'BAIXANDO'
  | 'EXTRAINDO'
  | 'CLASSIFICANDO'
  | 'PROCESSANDO_MIDIA'
  | 'REVISAO_MANUAL'
  | 'CONCLUIDO'
  | 'ERRO'
  | 'CANCELADO'

export type SourceType =
  | 'GOOGLE_DRIVE'
  | 'DROPBOX'
  | 'ONEDRIVE'
  | 'WETRANSFER'
  | 'S3_URL'
  | 'HTTP_URL'
  | 'ZIP_UPLOAD'
  | 'DIRECT_UPLOAD'
  | 'FTP'

export type TipoMedia = 'IMAGE' | 'VIDEO' | 'PDF' | 'DOCUMENT' | 'AUDIO'

export type CategoriaMedia =
  | 'FACHADA'
  | 'AREA_DE_LAZER'
  | 'PISCINA'
  | 'ACADEMIA'
  | 'SALAO_DE_FESTAS'
  | 'PLAYGROUND'
  | 'PLANTA_BAIXA'
  | 'PLANTA_HUMANIZADA'
  | 'PLANTA_3D'
  | 'LOGO'
  | 'BANNER'
  | 'POST_INSTAGRAM'
  | 'POST_FACEBOOK'
  | 'VIDEO_TOUR'
  | 'VIDEO_DRONE'
  | 'VIDEO_APRESENTACAO'
  | 'PDF_FOLDER'
  | 'PDF_MEMORIAL'
  | 'TABELA_PRECO'
  | 'DOCUMENTO_COMERCIAL'
  | 'QUARTO'
  | 'SALA'
  | 'COZINHA'
  | 'BANHEIRO'
  | 'VARANDA'
  | 'AREA_GOURMET'
  | 'VISTA'
  | 'MAPA_LOCALIZACAO'
  | 'OBRA'
  | 'OUTRO'

export type ClassificacaoMetodo =
  | 'NOME_ARQUIVO'
  | 'ESTRUTURA_PASTA'
  | 'IA_VISUAL'
  | 'OCR'
  | 'METADATA'
  | 'MANUAL'
  | 'COMBINADO'

export type PerfilVersao =
  | 'THUMBNAIL'
  | 'CARD'
  | 'BANNER'
  | 'MOBILE'
  | 'GALLERY'
  | 'FULLSCREEN'
  | 'SQUARE'
  | 'WEBP_ORIGINAL'
  | 'VIDEO_HLS'
  | 'VIDEO_MP4_LQ'
  | 'VIDEO_MP4_HQ'
  | 'VIDEO_THUMB'

export type StatusArquivo =
  | 'PENDENTE'
  | 'BAIXANDO'
  | 'PROCESSANDO'
  | 'CLASSIFICANDO'
  | 'CONCLUIDO'
  | 'ERRO'
  | 'IGNORADO'

export type TipoGaleria =
  | 'PRINCIPAL'
  | 'FACHADA'
  | 'PLANTA'
  | 'LAZER'
  | 'INTERIORES'
  | 'VIDEO'
  | 'DOCUMENTOS'
  | 'OBRA'

export type TipoDocumento =
  | 'FOLDER'
  | 'MEMORIAL_DESCRITIVO'
  | 'TABELA_PRECO'
  | 'PLANTA_PDF'
  | 'CONTRATO'
  | 'HABITE_SE'
  | 'OUTRO'
